Repository 0xOpenBytes/Site, pull requests merged in 2023-02, with the labels that each got.

#7 added adapter post
  src/content/blog/adapters.md
Labels: new article

#10 Add Projects
  src/components/Header.astro
  src/config.ts
  src/content/_schemas.ts
  src/content/config.ts
  src/content/projects/images/ios-base-icon.png
  src/content/projects/images/openbytes-t.png
  src/content/projects/ios-base.md
  src/content/projects/project-template.md
  src/content/projects/t.md
  src/layouts/ProjectDetails.astro
  src/layouts/Projects.astro
  src/pages/posts/[slug].astro
  src/pages/projects/[slug].astro
  src/pages/projects/index.astro
  src/styles/base.css
  src/utils/getSortedProjects.ts
Labels: enhancement

#13 Fixes Images
  public/assets/projects/images/ios-base-icon.png
  public/assets/projects/images/openbytes-t.png
  src/content/projects/ios-base.md
  src/content/projects/project-template.md
  src/content/projects/t.md
Labels: bug

#14 Update image paths
  src/content/projects/ios-base.md
  src/content/projects/t.md
Labels: bug

#15 Remove template tag resulting in a 404
  src/content/projects/ios-base.md
Labels: bug

#16 Fix Project `t` repo link
  src/content/projects/t.md
Labels: article edit

#17 added o and c
  public/assets/projects/images/openbytes-c.png
  public/assets/projects/images/openbytes-o.png
  src/content/projects/c.md
  src/content/projects/o.md
Labels: enhancement, new article

#18 Fix warnings and post slugs
  src/config.ts
  src/content/project/c.md
  src/content/project/ios-base.md
  src/content/project/o.md
  src/content/project/t.md
  src/layouts/ProjectDetails.astro
  src/layouts/Projects.astro
  src/pages/projects/[slug].astro
  src/pages/projects/index.astro
  src/utils/getSortedProjects.ts
Labels: bug, article edit

#19 Add project URLS
  src/content/project/c.md
  src/content/project/o.md
  src/pages/projects/index.astro
Labels: bug, article edit

#20 Adds Members to About Page
  src/components/Members.astro
  src/layouts/AboutLayout.astro
  src/pages/about.md
Labels: enhancement

#21 replaced astro paper image
  public/astropaper-og.jpg
  public/openbytes-og.png
  src/config.ts
Labels: enhancement

#22 hotfix for config site
  src/config.ts
Labels: bug

#25 Add Array Article
  src/content/blog/eliminating-array-duplicates.md
Labels: new article

#26 Update eliminating-array-duplicates.md
  src/content/blog/eliminating-array-duplicates.md
Labels: article edit

#27 Add OpenBytes favicon
  .prettierignore
  public/android-chrome-192x192.png
  public/android-chrome-384x384.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/favicon.svg
  public/mstile-150x150.png
  public/safari-pinned-tab.svg
  public/site.webmanifest
  src/layouts/Layout.astro
Labels: enhancement
